[package]
name = "spider-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.12"
thiserror = "1.0.37"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "mysql"] }